### ISSUE TITLE
Document Configuration File in Wiki

### ISSUE THREAD

**Issue by gianlucafrei** [gianlucafrei/Application-Gateway#22]
We should document all settings from the configuration file in the wiki (https://github.com/gianlucafrei/nellygateway/wiki)

Some are already implemented
- [x] Routes
- [x] Login providers
- [x] Session Behaviour 
- [x] Security Profiles
- [x] Top level settings (Host uri, trustedRedirectHosts,...)

**Comment by Padi-owasp** [comment]
IMO this is done: https://github.com/gianlucafrei/Application-Gateway/wiki/Configuration
