### ISSUE TITLE
Implement Bean Naming Schema

### ISSUE THREAD

**Issue by gianlucafrei** [gianlucafrei/Application-Gateway#83]
Currently we have a bit of anarchy when it comes to bean naming convention.
We should implement the following approach for all types of beans (shortName + postfix from variable in interface):

```java
public interface UserMappingFactory {

    /**
     * Name postfix for beans of this type.
     */
    String USER_MAPPER_TYPE_POSTFIX = "-userMapping-factory";

   [...]
}
```

```java

@Component("jwt-mapping" + USER_MAPPER_TYPE_POSTFIX)
public class JwtTokenMapperFactory implements UserMappingFactory {
    [...]
}
```

**Comment by groscy** [comment]
Why not just use the default naming strategy from Spring? (see https://www.baeldung.com/spring-bean-names#1-class-level-annotations)
If the classes are named accordingly the post fix can be achieved without any string constants in the interface

**Comment by groscy** [comment]
Proposal done, but no rights to push on repo

**Comment by Padi-owasp** [comment]
Proposal looks good, sorry it took us so long. I missed your PR. The notification got stuck in my Spam folder.
I'm working to include your proposal and make sure the documentation is in line with the changes too.
